#!/command/with-contenv sh
if [ -z "${SUB_URL}" ]; then
    echo "Error: $SUB_URL. Not starting HiddifyCli."
    exit 1
fi
exec ${BASE_PATH}/hiddify/HiddifyCli run -c $SUB_URL -d ${BASE_PATH}/hiddify/hiddify.json